// docs/frameworks/vue/App.vue
<script setup>
    import Molecule from './Molecule.vue';

    const options = {width: 300, height: 200};
</script>

<template>
    <div>
        <Molecule :options="options" smiles="C" />
        <Molecule :options="options" smiles="CC" />
        <Molecule :options="options" smiles="CCC" />
        <Molecule :options="options" smiles="CCCC" />
    </div>
</template>

// docs/frameworks/svelte/App.svelte
<script>
    import Molecule from './Molecule.svelte';

    const options = {width: 300, height: 200};
</script>

<div>
    <Molecule options={options} smiles="C" />
    <Molecule options={options} smiles="CC" />
    <Molecule options={options} smiles="CCC" />
    <Molecule options={options} smiles="CCCC" />
</div>
